# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.Endereco'),
        ),
    ]
