# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('PB', 'Paraiba'), ('PE', 'Pernambuco')], max_length=255),
        ),
    ]
