# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170222_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('BT', 'Banho e Tosa'), ('V', 'Vacinacao'), ('C', 'Castracao')], max_length=255)),
            ],
        ),
    ]
